export const KEYBOARD_LAYOUT = [
  { key: "A", x: 0, y: 0, is_pressed: false },
  { key: "Z", x: 1, y: 0, is_pressed: false },
  { key: "E", x: 2, y: 0, is_pressed: false },
  { key: "R", x: 3, y: 0, is_pressed: false },
  { key: "T", x: 4, y: 0, is_pressed: false },
  { key: "Y", x: 5, y: 0, is_pressed: false },
  { key: "U", x: 6, y: 0, is_pressed: false },
  { key: "I", x: 7, y: 0, is_pressed: false },
  { key: "O", x: 8, y: 0, is_pressed: false },
  { key: "P", x: 9, y: 0, is_pressed: false },
  { key: "Q", x: 0.5, y: 1, is_pressed: false },
  { key: "S", x: 1.5, y: 1, is_pressed: false },
  { key: "D", x: 2.5, y: 1, is_pressed: false },
  { key: "F", x: 3.5, y: 1, is_pressed: false },
  { key: "G", x: 4.5, y: 1, is_pressed: false },
  { key: "H", x: 5.5, y: 1, is_pressed: false },
  { key: "J", x: 6.5, y: 1, is_pressed: false },
  { key: "K", x: 7.5, y: 1, is_pressed: false },
  { key: "L", x: 8.5, y: 1, is_pressed: false },
  { key: "M", x: 9.5, y: 1, is_pressed: false },
  { key: "W", x: 1, y: 2, is_pressed: false },
  { key: "X", x: 2, y: 2, is_pressed: false },
  { key: "C", x: 3, y: 2, is_pressed: false },
  { key: "V", x: 4, y: 2, is_pressed: false },
  { key: "B", x: 5, y: 2, is_pressed: false },
  { key: "N", x: 6, y: 2, is_pressed: false },
];
